import Head from 'next/head'
import { useQ}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Next JS</h1>
      </main>
    </div>
  );
}
 